### ISSUE TITLE
bug: oklch-color-picker: thread 'main' panicked at src/main.rs:66:6:

### ISSUE THREAD

**Issue by jemag** [eero-lehtinen/oklch-color-picker.nvim#3]
### Neovim version (nvim -v)

NVIM v0.11.0-dev-1369+gb03e790cdd

### Operating system/version

Arch WSL Linux 5.15.167.4-microsoft-standard-WSL2

### Describe the bug

Trying to launch the picker results in `oklch-color-picker: thread 'main' panicked at src/main.rs:66:6:`

It seems like the picker application itself will not launch. Here is the backtrace launch:
![image](https://github.com/user-attachments/assets/250d1b8e-a2b6-451f-9a0a-b8404e04c84a)
and the full backtrace
![image](https://github.com/user-attachments/assets/8da298dd-4f48-43e1-a009-1628867dfd2b)

### Steps To Reproduce

1. Go on color
2. Launch color picker
3. Notice error

### Expected Behavior

Picker launches

**Comment by jemag** [comment]
I have just realized that the binary is an actual graphical application hence why it likely won't work trying to launch from WSL.

If the OS is WSL (perhaps detected through env variable such as `WSL_INTEROP`), could we simply download the windows `.exe`  and use that instead? 

I have donwloaded the `exe` and the picker works just fine on the Windows side.

**Comment by eero-lehtinen** [comment]
The error means that it doesn't detect X11 or Wayland on your system. I haven't tested it but I'm pretty sure it should work with automatically with WSLg. Maybe you need to setup DISPLAY or WAYLAND_DISPLAY env vars. I can also look into it later.

**Comment by eero-lehtinen** [comment]
Also yeah for now you maybe could just drop the exe in the lazy install folder so it gets used instead of the Linux version for now until I fix this. (Though that might also not work depending how the exe is resolved)

**Comment by jemag** [comment]
I can open the .exe fine, both if it is located on the windows or WSL side, although I cannot replace it in the lazy install folder as it seems the plugin will continuously try to re-download and overwrite it

**Comment by eero-lehtinen** [comment]
I tried it myself and for some reason this specific app doesn't seem to run on WSLg, even though things like xeyes run fine. I got a different error though, maybe because I used the default Ubuntu distro.

Normally:
```
$ ./oklch-color-picker
thread 'main' panicked at src/main.rs:66:6:
called `Result::unwrap()` on an `Err` value: WinitEventLoop(Os(OsError { line: 81, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoCompositor)) }))
```

With X11 it works (after deleting WAYLAND_DISPLAY environment variable)
```
$ WAYLAND_DISPLAY= ./oklch-color-picker
```

But I don't really want to debug it and using the windows version seems to work fine and is probably more performant, so lets just do that.
